function [fitresult, gof] = PoissonFit(X, Y,PeakRange,Niters,doFig)
%CREATEFIT(X2,Y2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X2
%      Y Output: Y2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Aug-2016 16:59:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'a*x*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-100 -100 -100];
opts.Robust = 'Bisquare';
opts.Upper = [100 100 100];
ExpectedPeakRange=linspace(PeakRange(1),PeakRange(end),Niters);

% Fit model to data.
for i=1:length(ExpectedPeakRange)
    opts.StartPoint = [0 1/ExpectedPeakRange(i) 0];
    try
        [fitresult{i}, gof{i}] = fit( xData, yData, ft, opts );
        R2(i)=gof{i}.adjrsquare;
    catch
        disp('Poisson Fit Error...')
        R2(i)=-inf;
    end
end
[R2max,I]=max(R2);
if R2max>-inf
    fitresult=fitresult{I};
    gof=gof{I};
else
    fitresult=nan;
    gof=nan;
end

if doFig
    % Plot fit with data.
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData, 'PredFunc'); %'predobs' );
    %     hold on; plot(xData,p22,'m--')
    legend( h, 'Measures vs. AGES', 'untitled fit 1', 'Lower bounds (untitled fit 1)', 'Upper bounds (untitled fit 1)', 'Location', 'NorthEast' );
    % Label axes
    xlabel( 'AGES' );
    ylabel( 'Measurement' );
    grid on
end


