function [fitresult, gof] = Poly2Fit(X, Y,doFig)
%CREATEFITS(AGES,MTEDGE,MDEDGE,ICVFEDGE)
%  Create 2nd-order polynomial fits. 
% 
%  Data for 'untitled fit 1' fit:
%      X Input : e.g. AGES
%      Y Output: e.g. MTedge
%      doFig : logical for whether to generate figure.
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Feb-2016 14:06:32

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 3, 1 );
gof = struct( 'sse', cell( 3, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

[X,I]=sort(X);
Y=Y(I);

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf];
opts.Robust = 'Bisquare';
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% p22=predint(fitresult,xData,0.95,'functional','off');

if doFig
    % Plot fit with data.
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, xData, yData, 'PredFunc'); %'predobs' );
%     hold on; plot(xData,p22,'m--')
    legend( h, 'Measures vs. AGES', 'untitled fit 1', 'Lower bounds (untitled fit 1)', 'Upper bounds (untitled fit 1)', 'Location', 'NorthEast' );
    % Label axes
    xlabel( 'AGES' );
    ylabel( 'Measurement' );
    grid on
end

