function [fitresult, gof] = Poly1Fit(X, Y, doFig)
%CREATEFITS(X,Y)
%  Create fits.
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Feb-2016 17:01:03

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 4, 1 );
gof = struct( 'sse', cell( 4, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

[X,I]=sort(X);
Y=Y(I);

%% Fit: 'untitled fit 4'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf];
opts.Robust = 'Bisquare';
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
p22=predint(fitresult,xData,0.95,'functional','off');

if doFig
    % Plot fit with data.
    figure( 'Name', 'untitled fit 4' );
    h = plot( fitresult, xData, yData, 'PredFunc'); %'predobs' );
%     hold on; plot(xData,p22,'m--')
    legend( h, 'Y vs. X', 'untitled fit 4', 'Location', 'NorthEast' );
    % Label axes
    xlabel( 'X' );
    ylabel( 'Y' );
    grid on
end

